import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: appTheme.whiteA700,
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: appTheme.gray200,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blueGray50,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray300,
          fontSize: getFontSize(
            10,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: getFontSize(
            50,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            26,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray500,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: appTheme.gray60001,
          fontSize: getFontSize(
            10,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            9,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF227DDE),
    primaryContainer: Color(0XFF1A1F71),
    secondary: Color(0XFF1A1F71),
    secondaryContainer: Color(0XFF219ADE),
    tertiary: Color(0XFF1A1F71),
    tertiaryContainer: Color(0XFF219ADE),

    // Background colors
    background: Color(0XFF1A1F71),

    // Surface colors
    surface: Color(0XFF1A1F71),
    surfaceTint: Color(0XFF101522),
    surfaceVariant: Color(0XFF219ADE),

    // Error colors
    error: Color(0XFF101522),
    errorContainer: Color(0XFF555555),
    onError: Color(0XFF898A8D),
    onErrorContainer: Color(0XFF101522),

    // On colors(text colors)
    onBackground: Color(0XFFD3D6DA),
    onInverseSurface: Color(0XFF898A8D),
    onPrimary: Color(0XFF101522),
    onPrimaryContainer: Color(0XFFD3D6DA),
    onSecondary: Color(0XFFD3D6DA),
    onSecondaryContainer: Color(0XFF101522),
    onTertiary: Color(0XFFD3D6DA),
    onTertiaryContainer: Color(0XFF101522),

    // Other colors
    outline: Color(0XFF101522),
    outlineVariant: Color(0XFF1A1F71),
    scrim: Color(0XFF1A1F71),
    shadow: Color(0XFF101522),

    // Inverse colors
    inversePrimary: Color(0XFF1A1F71),
    inverseSurface: Color(0XFF101522),

    // Pending colors
    onSurface: Color(0XFFD3D6DA),
    onSurfaceVariant: Color(0XFF101522),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFBBC05);

  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue50 => Color(0XFFEDF5FC);
  Color get blue5001 => Color(0XFFEDF4FC);
  Color get blue5002 => Color(0XFFECF4FB);
  Color get blue600 => Color(0XFF3577E5);
  Color get blue700 => Color(0XFF216DDE);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray300 => Color(0XFFA0A7B0);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray50 => Color(0XFFE8F3F1);
  Color get blueGray800 => Color(0XFF3B4453);
  Color get blueGray80001 => Color(0XFF3B4353);

  // Cyan
  Color get cyan100 => Color(0XFFC0F3EE);

  // Gray
  Color get gray100 => Color(0XFFF2F2F2);
  Color get gray200 => Color(0XFFE5E7EB);
  Color get gray400 => Color(0XFFC4C4C4);
  Color get gray500 => Color(0XFFADADAD);
  Color get gray600 => Color(0XFF707684);
  Color get gray60001 => Color(0XFF727272);
  Color get gray60002 => Color(0XFF717784);
  Color get gray700 => Color(0XFF646464);
  Color get gray800 => Color(0XFF464646);
  Color get gray900 => Color(0XFF101623);

  // Red
  Color get red300 => Color(0XFFFB6868);
  Color get red50 => Color(0XFFFFEAEA);
  Color get red500 => Color(0XFFEA4335);
  Color get redA200 => Color(0XFFFF5C5C);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
  Color get whiteA70001 => Color(0XFFFFFFFE);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
